server:
  port: 10010

spring:
  redis:
    host: 192.168.154.129
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/mrmy?useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: tm-gateway
  cloud:
    nacos:
      server-addr: localhost:8848  # nacos地址
    gateway:
      routes:
          # 路由标识，必须唯一
        - id: home-server
          # 路由的目标地址（服务名）
          uri: lb://tm-home
          # 路由断言，判断请求是否符合规则
          predicates:
            # 路径断言，判断路径是否是以/user开头，如果是则符合
            - Path=/home/**


