server:
  port: 8080

spring:
  application:
    name: tm-alipay
  datasource:
    url: jdbc:mysql://localhost:3306/mrmy?useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  type-aliases-package: com.tm.entity
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      #主键自增
      id-type: auto
      table-underline: true
      table-prefix: t_
      schema: yfy
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

alipay:
  appId: 2021000121660691
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCGkNVIP7cXMndd7j8+0G1+PodYpLQKkPY6W0Yc14W6D9lWFptSdNHQXynQxlTCljaDuQKbTwPiqf7IWeV8MhmNG8KVh8AUAi5HGTffbpQBOYZLtTRHeqMniqeLBT6S9E3dQXy/HYUhV8y4NpVwZL4MmZv3UfRqWTesMUIrD549lEWrpK/hVp3cCEe5Y08K0OZTWAlxwicI32B3eGmWhfnyi5AEydxju3znOu+/UxwGXP0wU/zRe9XrbI0ECjVyl8UnnBYsPHLPwRVjvkp4Gb/iHA+aILNigjrnv5xr8UtzF1iLn7D2vul6gt168gVQLOtJ0INiQGuJ2J1ffFDmb73tAgMBAAECggEAbq6YT3ngzdq7pe395Vuog+tIhhfK4toDPVKv468+FiFNIWsszHC71wk/KrLHKtpE8qltRHOEfZ5Xq1GN2U6YB6GqtjVXPt3gVKigdU3NvQgktwbPfm+X3UFFt6pToqoBlZh00/mi9B70ixySZETosRJz38RwJj1F9oL5qtOI05p1PDNSgWcPokSY7M4JN/9ZCET4uqqUObtddv+REImveYvL4rmpYX6CyCqzl4MgqalFI8DXeqAZG4hQht++x1tZXHY2b8JiWZjRdra62lmtgAOcc1ka0HUx9dvTdkMA30QZ5Ykg5e6RHFmht5PUlRbMKGuyMJCwIdDaUI9E6UV8AQKBgQDpH9srJZr+Vzu1sf1Q1Dn81sIj5LBijTDqRASLb1zoAwSFMNETcxB41Y68f0od4IKNNJ9ynPjTKMJayRo+RRsAyM/CRwTwax+NRCEAuWtiw68AR3/WqLm9xlH+z/guVx3FXw1JxXnzUJrnAPr8rwUBoeLTnabsRv1aSkP3tipk7QKBgQCTxSiKL8UFevLJFVA99wZgwKUR7t22k4iMe2WBl7SnyZrNHaRWBBjbPhpXpWzGclyMomh3vkB1TjvnJp/K/xGwx/uvqYuYqC0zzP+LTkR6htbPfYinwaIkgeg2SGQ9CUJDh1w39mDd96qpQVCufy8PFlmydtanFHZwKMsJReCdAQKBgQDTzYyb0+vQ/0KRnufuwxL4Q8pZQBJ9R5hUj32tjX1UkkFOHX8nc5hYoHaxjdix8mPKlS/0uudbOiHyx9mfD7wr50bTVSEIqdsdxvNRLCWDsxRRZaShS+SNphyjLSJoP+AdjXGOP+u/g9Fo5bwjTYR36jQiXY7mBs1ydhzwd0JnNQKBgFPEPRHwuHA93SluQpmN0fjA3BJJZTfddFemj8kh1ZAT8gP6nLECC5ElKEutA/eO1rYGTtAqcmHNIpoLRCQP6dhb1Woj43V7SHyH5gjzKlCG5XijwfbPBnpJhfhXmzMab4zWS8mRiiHqBr2BwBnbETMtSVWollAKgoVcKpSsHwMBAoGAJrUzarSgSBhluclP3GkxBJA0Q8+YmFhN0NLvRtQ8fCw1Db2mL0Z4ALKaYc51c/CTChmwp3zl2sCzoCL9gJSyCuYV9185jSQhXyEaiR/Y74BWRptmaxsJGtHOJxHNXH/IDdAjSievAKM4zWf1zmp8HTYz5dOYP5a1BD6lZ9wQcfI=
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhpDVSD+3FzJ3Xe4/PtBtfj6HWKS0CpD2OltGHNeFug/ZVhabUnTR0F8p0MZUwpY2g7kCm08D4qn+yFnlfDIZjRvClYfAFAIuRxk3326UATmGS7U0R3qjJ4qniwU+kvRN3UF8vx2FIVfMuDaVcGS+DJmb91H0alk3rDFCKw+ePZRFq6Sv4Vad3AhHuWNPCtDmU1gJccInCN9gd3hploX58ouQBMncY7t85zrvv1McBlz9MFP80XvV62yNBAo1cpfFJ5wWLDxyz8EVY75KeBm/4hwPmiCzYoI657+ca/FLcxdYi5+w9r7peoLdevIFUCzrSdCDYkBrididX3xQ5m+97QIDAQAB
  #支付网关配置，这一项是写死的，正式环境是openapi.alipay.com
  gateway: openapi.alipaydev.com
  #支付成功之后的回调页面，只是一个友好页面。主要换成你自己映射的临时域名
  returnUrl: http://kmrf93.natappfree.cc/paySuccess/paySuccess
  #支付成功的接口回调，我们还没写，先空着
  notifyUrl: http://kmrf93.natappfree.cc/paySuccess/paySuccess